// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/OVantsevich/GolangInternship/FMicroservice/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Stream is an autogenerated mock type for the Stream type
type Stream struct {
	mock.Mock
}

// ProduceUser provides a mock function with given fields: ctx, user
func (_m *Stream) ProduceUser(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStream interface {
	mock.TestingT
	Cleanup(func())
}

// NewStream creates a new instance of Stream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStream(t mockConstructorTestingTNewStream) *Stream {
	mock := &Stream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
