// Code generated by mockery v2.16.0. DO NOT EDIT.

package service

import (
	context "context"

	model "GolangInternship/FMicroserviceGRPC/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockStream is an autogenerated mock type for the Stream type
type MockStream struct {
	mock.Mock
}

// ProduceUser provides a mock function with given fields: ctx, user
func (_m *MockStream) ProduceUser(ctx context.Context, user *model.User) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockStream interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockStream creates a new instance of MockStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockStream(t mockConstructorTestingTNewMockStream) *MockStream {
	mock := &MockStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
